% Not a function in order to share main workspace scope

% This whole file would be better done with object oriented programming (i.e. classes)
version_number = '0.0.1';

%% Compiler Constants
global compiler;
compiler.active = 'cura';
compiler.cura.layer_marker = "^;LAYER:[0-9]+";

%% gcode flavor Constants
global flavor;
flavor.active = "marlin";
flavor.marlin.movement_call = '^G0 ';
flavor.marlin.e_movement_call = '^G1 ';
flavor.marlin.absolute_mode_call = '^G90 ';
flavor.marlin.relative_mode_call = '^G91 ';
flavor.marlin.set_position_call = '^G92 ';
flavor.marlin.pause_print_call = '^M25 ';

%% Printer Constants
% Ender 3 V2 Printer
printer.ender3v2.name = "Ender 3 v2";
printer.ender3v2.starting_code = ["; Ender 3 v2 Custom Start G-code",char(10),...
"G92 E0 ; Reset Extruder",char(10),...
"G28 ; Home all axes",char(10),...
"G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed",char(10),...
"G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position",char(10),...
"G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line",char(10),...
"G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little",char(10),...
"G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line",char(10),...
"G92 E0 ; Reset Extruder",char(10),...
"G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed",char(10),...
"G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish"];
printer.ender3v2.ending_code = ["G91 ;Relative positioning",char(10),...
"G1 E-2 F2700 ;Retract a bit",char(10),...
"G1 E-2 Z0.2 F2400 ;Retract and raise Z",char(10),...
"G1 X5 Y5 F3000 ;Wipe out",char(10),...
"G1 Z10 ;Raise Z more",char(10),...
"G90 ;Absolute positionning"];
printer.ender3v2.flavor = "marlin";
% For relative position error checking, should position changes be implemented in the future.
printer.ender3v2.bed_size.x = 220;
printer.ender3v2.bed_size.y = 220;
printer.ender3v2.bed_size.z = 250;